Applications/routes/web.php
<?php

Route::get('/home', function () {
    return redirect()->route('admin.dashboard');
});

Route::get('/', 'HomeController@index')->name('home');
Route::get('/articles', 'PostController@index');
Route::get('/daftar-isi', 'PostController@toc');

Route::get('/search', 'SearchController@search')->name('search');
Route::get('/search/getdata', 'SearchController@getData')->name('search.getdata');

Route::get('/templates', function () {
    return view('new-template');
});

Route::get('posts', 'PostController@index')->name('post.index');
Route::get('post/{slug}', 'PostController@detail')->name('post.detail');

Route::get('/category/{slug}', 'PostController@postByCategory')->name('category.posts');
Route::get('/tag/{slug}', 'PostController@postByTag')->name('tag.posts');

Route::post('subscriber', 'SubscriberController@store')->name('subscriber.store');
Auth::routes();

Route::group(['middleware'=> ['auth']], function (){
   Route::post('favorite/{post}/add', 'FavoriteController@add')->name('post.favorite');
   Route::post('comment/{post}', 'CommentController@store')->name('comment.store');
});

Route::group(['as'=>'admin.', 'prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth', 'admin']], function (){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('setting/general', 'SettingsController@index')->name('setting');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    Route::resource('tag', 'TagController');
    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');

    Route::get('/pending/post', 'PostController@pending')->name('post.pending');
    Route::put('/post/{id}/approve', 'PostController@approval')->name('post.approve');

    Route::get('/favorite', 'FavoriteController@index')->name('favorite.index');

    Route::get('authors', 'AuthorController@index')->name('author.index');
    Route::delete('authors/{id}', 'AuthorController@destroy')->name('author.destroy');

    Route::get('comments', 'CommentController@index')->name('comment.index');
    Route::delete('comments/{id}', 'CommentController@destroy')->name('comment.destroy');

    Route::get('/subscriber', 'SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{subscriber}', 'SubscriberController@destroy')->name('subscriber.destroy');
});

Applications/app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AuthorController extends Controller
{
    public function index()
    {
       $authors = User::authors()
           ->withCount('posts')
           ->withCount('comments')
           ->withCount('favorite_posts')
           ->get();
       return view('admin.authors',compact('authors'));
    }

    public function destroy($id)
    {
        $author = User::findOrFail($id)->delete();
        Toastr::success('Author Successfully Deleted','Success');
        return redirect()->back();
    }
}

Applications/resources/views/admin/authors.blade.php
@extends('layouts.master')

@section('title','Authors')
@section('breadcrumb')
    @parent
    <li class="breadcrumb-item">Authors</li>
@endsection

@section('main-content')
 @card
        @slot('title')
            <h5 class="card-title">All Authors</h5>
        @endslot

        @table
            @slot('thead')
                <th>ID</th>
                <th>Name</th>
                <th>Posts</th>
                <th>Comments</th>
                <th>Favorite Posts</th>
                <th>Created At</th>
                <th>Action</th>
            @endslot
            @foreach($authors as $key => $author)
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td>{{ $author->name }}</td>
                    <td>{{ $author->posts_count }}</td>
                    <td>{{ $author->comments_count }}</td>
                    <td>{{ $author->favorite_posts_count }}</td>
                    <td>{{ $author->created_at->toDateString() }}</td>
                    <td class="text-center">
                        <form id="delete-form-{{ $author->id }}" action="{{ route('admin.author.destroy',$author->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger btn-sm" onclick="deleteAuthors({{ $author->id }})"><i class="fas fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
            @endforeach
        @endtable

        @slot('footer')
            
        @endslot
    @endcard
@endsection

@push('scripts')
    <script>
        $('.table').DataTable({
            "language": {
              "emptyTable": "Ups data masih kosong!.",
              "zeroRecords": "Ups data tidak ditemukan!."
            }
        })

        $('.card-footer').hide()
    </script>
@endpush

Applications/resources/views/admin/comments.blade.php
@extends('layouts.master')

@section('title','Comments')
@section('breadcrumb')
    @parent
    <li class="breadcrumb-item">Comments</li>
@endsection

@section('main-content')
    @card
        @slot('title')
            <h5 class="card-title">All Comments</h5>
        @endslot

        @table
            @slot('thead')
                <th>Comments Info</th>
                <th>Post Info</th>
                <th>Action</th>
            @endslot

            @foreach($comments as $key => $comment)
            <tr>
                <td>
                    <div class="media">
                        <a href="#">
                            <img class="mr-3" src="{{ Storage::disk('public')->url('profile/'.$comment->user->image) }}" width="64" height="64">
                        </a>
                        <div class="media-body">
                            <h5 class="mt-0">{{ $comment->user->name }} <small class="text-muted">{{ $comment->created_at->diffForHumans() }}</small></h5>
                            <p>{{ $comment->comment }}</p>
                            <a class="btn btn-primary btn-sm float-right" target="_blank" href="{{ route('post.detail',$comment->post->slug.'#comments') }}"><i class="fas fa-reply"></i> </a>
                        </div>
                    </div>
                </td>
                <td>
                    <div class="media">
                        <a target="_blank" href="{{ route('post.detail', $comment->post->slug) }}">
                            <img class="mr-3" src="{{ Storage::disk('public')->url('post/'.$comment->post->image) }}" width="64" height="64">
                        </a>
                        <div class="media-body">
                            <a target="_blank" href="{{ route('post.detail',$comment->post->slug) }}">
                                <h5 class="mt-0">{{ $comment->post->title }}</h5>
                            </a>
                            <p>By: <strong>{{ $comment->post->user->name }}</strong></p>
                        </div>
                    </div>
                </td>
                <td>
                    <form method="POST" action="{{ route('admin.comment.destroy', $comment->id) }}" >
                        @csrf
                        @method('DELETE')

                        <button type="button" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?')"><i class="fas fa-trash"></i></button>
                    </form>
                </td>
            </tr>
            @endforeach
        @endtable

        @slot('footer')
            
        @endslot
    @endcard
@endsection

@push('scripts')
    <script>
        $('.table').DataTable({
            "language": {
              "emptyTable": "Ups data masih kosong!.",
              "zeroRecords": "Ups data tidak ditemukan!."
            }
        })

        $('.card-footer').hide()
    </script>
@endpush

Applications/resources/views/admin/favorite.blade.php
@extends('layouts.master')

@section('title','Posts')
@section('breadcrumb')
    @parent
    <li class="breadcrumb-item">Posts</li>
@endsection

@section('main-content')
    @card
        @slot('title')
            <a href="{{ route('admin.post.create') }}" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Add</a>
        @endslot
        
        @table

            @slot('thead')
                <th>ID</th>
                <th>Title</th>
                <th>Author</th>
                <th><i class="fas fa-eye"></i></th>
                <th>Is Approved</th>
                <th>Status</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>Action</th>
            @endslot
                                    
            @foreach($posts as $key => $post)
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td title="{{ $post->title }}">{{ str_limit($post->title, '40') }}</td>
                    <td>{{ $post->user->name }}</td>
                    <td>{{ $post->view_count }}</td>
                    <td>
                        @if($post->is_approved == true)
                            <span class="badge bg-primary">Approved</span>
                        @else
                            <span class="badge bg-danger">Pending</span>
                        @endif
                    </td>
                    <td>
                        @if($post->status == true)
                            <span class="badge bg-primary">Published</span>
                        @else
                            <span class="badge bg-danger">Pending</span>
                        @endif
                    </td>
                    <td>{{ $post->created_at->toDateString() }}</td>
                    <td>{{ $post->updated_at->toDateString() }}</td>

                    <td class="text-center">
                        <form action="{{ route('admin.post.destroy', $post->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                             <a href="{{ route('admin.post.show',$post->id) }}" class="btn btn-outline-primary btn-sm"><i class="fas fa-eye"></i></a>
                            <a href="{{ route('admin.post.edit',$post->id) }}" class="btn btn-primary btn-sm"><i class="fas fa-edit"></i></a>
                            <button class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?')"><i class="fas fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
            @endforeach
        @endtable

        @slot('footer')
            
        @endslot
    @endcard
@endsection

@push('scripts')
    <script>
        $('.table').DataTable({
            "language": {
              "emptyTable": "Ups data masih kosong!.",
              "zeroRecords": "Ups data tidak ditemukan!."
            }
        })

        $('.card-footer').hide()
    </script>
@endpush

Applications/resources/views/admin/settings.blade.php
@extends('layouts.master')

@section('title','Settings')
@section('breadcrumb')
    @parent
    <li class="breadcrumb-item">Settings</li>
@endsection

@section('main-content')
    @card
        @slot('title')
            <ul class="nav nav-pills" id="pills-tab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Update Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Change Password</a>
                </li>
            </ul>
        @endslot
        
        <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                <form method="POST" action="{{ route('admin.profile.update') }}" class="form-horizontal" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                            <label for="name">Name : </label>
                        </div>
                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                            <div class="form-group">
                                <div class="form-line">
                                    <input type="text" id="name" class="form-control" placeholder="Enter your name" name="name" value="{{ Auth::user()->name }}">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                            <label for="email_address_2">Email Address</label>
                        </div>
                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                            <div class="form-group">
                                <div class="form-line">
                                    <input type="text" id="email_address_2" class="form-control" placeholder="Enter your email address" name="email" value="{{ Auth::user()->email }}">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                            <label for="email_address_2">Profile Image : </label>
                        </div>
                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                            <div class="form-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="customFile" name="image">
                                    <label class="custom-file-label" for="customFile">Choose file</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                            <label for="email_address_2">About : </label>
                        </div>
                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                            <div class="form-group">
                                <div class="form-line">
                                    <textarea rows="5" name="about" class="form-control">{{ Auth::user()->about }}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                            <button type="submit" class="btn btn-primary btn-sm">Update</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                <form method="POST" action="{{ route('admin.password.update') }}" class="form-horizontal">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                            <label for="old_password">Old Password : </label>
                        </div>
                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                            <div class="form-group">
                                <div class="form-line">
                                    <input type="password" id="old_password" class="form-control" placeholder="Enter your old password" name="old_password">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                            <label for="password">New Password : </label>
                        </div>
                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                            <div class="form-group">
                                <div class="form-line">
                                    <input type="password" id="password" class="form-control" placeholder="Enter your new password" name="password">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                            <label for="confirm_password">Confirm Password : </label>
                        </div>
                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                            <div class="form-group">
                                <div class="form-line">
                                    <input type="password" id="confirm_password" class="form-control" placeholder="Enter your new password again" name="password_confirmation">
                                </div>
                            </div>
                        </div>
                    </div>



                    <div class="row">
                        <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                            <button type="submit" class="btn btn-primary btn-sm">Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        
        @slot('footer')
            
        @endslot
    @endcard
@endsection

@push('scripts')
    <script>
        $('.card-header').addClass('m-0')
        $('.card-footer').hide()
    </script>
@endpush

Applications/resources/views/admin/subscriber.blade.php
@extends('layouts.master')

@section('title','Subscribers')
@section('breadcrumb')
    @parent
    <li class="breadcrumb-item">Subscribers</li>
@endsection

@section('main-content')
    @card
        @slot('title')
            <h5 class="card-title">All Subscribers</h5>
        @endslot

        @table
            @slot('thead')
                <th>ID</th>
                <th>Email</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>Action</th>
            @endslot

            @foreach($subscribers as $key => $subscriber)
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td>{{ $subscriber->email }}</td>
                    <td>{{ $subscriber->created_at->toDateString() }}</td>
                    <td>{{ $subscriber->updated_at->toDateString() }}</td>
                    <td class="text-center">
                        <button class="btn btn-danger btn-sm" type="button" onclick="$('#delete-form').submit()">
                            <i class="fas fa-trash"></i>
                        </button>
                        <form id="delete-form" action="{{ route('admin.subscriber.destroy',$subscriber->id) }}" method="POST" style="display: none;">
                            @csrf
                            @method('DELETE')
                        </form>
                    </td>
                </tr>
            @endforeach            
        @endtable

        @slot('footer')
            
        @endslot
    @endcard
@endsection

@push('scripts')
    <script>
        $('.table').DataTable({
            "language": {
              "emptyTable": "Ups data masih kosong!.",
              "zeroRecords": "Ups data tidak ditemukan!."
            }
        })

        $('.card-footer').hide()
    </script>
@endpush