Applications/routes/web.php
<?php

Route::get('/home', function () {
    return redirect()->route('admin.dashboard');
});

Route::get('/', 'HomeController@index')->name('home');
Route::get('/articles', 'PostController@index');
Route::get('/daftar-isi', 'PostController@toc');

Route::get('/search', 'SearchController@search')->name('search');
Route::get('/search/getdata', 'SearchController@getData')->name('search.getdata');

Route::get('/templates', function () {
    return view('new-template');
});

Route::get('posts', 'PostController@index')->name('post.index');
Route::get('post/{slug}', 'PostController@detail')->name('post.detail');

Route::get('/category/{slug}', 'PostController@postByCategory')->name('category.posts');
Route::get('/tag/{slug}', 'PostController@postByTag')->name('tag.posts');

Route::post('subscriber', 'SubscriberController@store')->name('subscriber.store');
Auth::routes();

Route::group(['middleware'=> ['auth']], function (){
   Route::post('favorite/{post}/add', 'FavoriteController@add')->name('post.favorite');
   Route::post('comment/{post}', 'CommentController@store')->name('comment.store');
});

Route::group(['as'=>'admin.', 'prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth', 'admin']], function (){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('setting/general', 'SettingsController@index')->name('setting');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    Route::resource('tag', 'TagController');
    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');

    Route::get('/pending/post', 'PostController@pending')->name('post.pending');
    Route::put('/post/{id}/approve', 'PostController@approval')->name('post.approve');

    Route::get('/favorite', 'FavoriteController@index')->name('favorite.index');

    Route::get('authors', 'AuthorController@index')->name('author.index');
    Route::delete('authors/{id}', 'AuthorController@destroy')->name('author.destroy');

    Route::get('comments', 'CommentController@index')->name('comment.index');
    Route::delete('comments/{id}', 'CommentController@destroy')->name('comment.destroy');

    Route::get('/subscriber', 'SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{subscriber}', 'SubscriberController@destroy')->name('subscriber.destroy');
});

Applications/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function categories()
    {
        return $this->belongsToMany('App\Category')->withTimestamps();
    }
    public function tags()
    {
        return $this->belongsToMany('App\Tag')->withTimestamps();
    }

    public function favorite_to_users()
    {
        return $this->belongsToMany('App\User')->withTimestamps();
    }

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

    public function scopeApproved($query)
    {
        return $query->where('is_approved', 1);
    }
    public function scopePublished($query)
    {
        return $query->where('status', 1);
    }
}

Applications/app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Notifications\AuthorPostApproved;
use App\Notifications\NewPostNotify;
use App\Subscriber;
use App\Tag;
use App\Post;
use Brian2694\Toastr\Facades\Toastr;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::latest()->get();
        return view('admin.post.index',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('admin.post.create',compact('categories','tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' => 'required',
            'image' => 'required',
            'categories' => 'required',
            'tags' => 'required',
            'body' => 'required',
        ]);
        
        $image = $request->file('image');
        $slug = str_slug($request->title);
        if(isset($image))
        {
//            make unipue name for image
            $currentDate = Carbon::now()->toDateString();
            $imageName  = $slug.'-'.$currentDate.'-'.uniqid().'.'.$image->getClientOriginalExtension();

            if(!Storage::disk('public')->exists('post'))
            {
                Storage::disk('public')->makeDirectory('post');
            }

            $postImage = Image::make($image)->resize(1600,1066)->save();
            Storage::disk('public')->put('post/'.$imageName,$postImage);

        } else {
            $imageName = "default.png";
        }
        $post = new Post();
        $post->user_id = Auth::id();
        $post->title = $request->title;
        $post->slug = $slug;
        $post->image = $imageName;
        $post->body = $request->body;
        if(isset($request->status))
        {
            $post->status = true;
        }else {
            $post->status = false;
        }
        $post->is_approved = true;
        $post->save();

        $post->categories()->attach($request->categories);
        $post->tags()->attach($request->tags);

        $subscribers = Subscriber::all();
        foreach ($subscribers as $subscriber)
        {
            Notification::route('mail',$subscriber->email)
                ->notify(new NewPostNotify($post));
        }

        Toastr::success('Post Successfully Saved :)','Success');
        return redirect()->route('admin.post.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('admin.post.show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::all();
        $tags = Tag::all();

        return view('admin.post.edit',compact('post','categories','tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $this->validate($request,[
            'title' => 'required',
            'image' => 'image',
            'categories' => 'required',
            'tags' => 'required',
            'body' => 'required',
        ]);
        $image = $request->file('image');
        $slug = str_slug($request->title);
        if(isset($image))
        {
//            make unipue name for image
            $currentDate = Carbon::now()->toDateString();
            $imageName  = $slug.'-'.$currentDate.'-'.uniqid().'.'.$image->getClientOriginalExtension();

            if(!Storage::disk('public')->exists('post'))
            {
                Storage::disk('public')->makeDirectory('post');
            }
//            delete old post image
            if(Storage::disk('public')->exists('post/'.$post->image))
            {
                Storage::disk('public')->delete('post/'.$post->image);
            }
            $postImage = Image::make($image)->resize(1600,1066)->save();
            Storage::disk('public')->put('post/'.$imageName,$postImage);

        } else {
            $imageName = $post->image;
        }

        $post->user_id = Auth::id();
        $post->title = $request->title;
        $post->slug = $slug;
        $post->image = $imageName;
        $post->body = $request->body;
        if(isset($request->status))
        {
            $post->status = true;
        }else {
            $post->status = false;
        }
        $post->is_approved = true;
        $post->save();

        $post->categories()->sync($request->categories);
        $post->tags()->sync($request->tags);

        Toastr::success('Post Successfully Updated :)','Success');
        return redirect()->route('admin.post.index');
    }

    public function pending()
    {
        $posts = Post::where('is_approved',false)->get();
        return view('admin.post.pending',compact('posts'));
    }

    public function approval($id)
    {
        $post = Post::find($id);
        if ($post->is_approved == false)
        {
            $post->is_approved = true;
            $post->save();
            $post->user->notify(new AuthorPostApproved($post));

            $subscribers = Subscriber::all();
            foreach ($subscribers as $subscriber)
            {
                Notification::route('mail',$subscriber->email)
                    ->notify(new NewPostNotify($post));
            }

            Toastr::success('Post Successfully Approved :)','Success');
        } else {
            Toastr::info('This Post is already approved','Info');
        }
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        if (Storage::disk('public')->exists('post/'.$post->image))
        {
            Storage::disk('public')->delete('post/'.$post->image);
        }
        $post->categories()->detach();
        $post->tags()->detach();
        $post->delete();
        Toastr::success('Post Successfully Deleted :)','Success');
        return redirect()->back();
    }
}

Applications/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Post;
use App\Tag;
use Request;
use Session;

class PostController extends Controller
{

    public function index()
    {
        $posts      = Post::latest()->approved()->published()->paginate(9);
        $latests    = Post::latest()->approved()->published()->take(8)->get();

        return view('new-article', compact('posts', 'latests'));
    }
    
    public function detail($slug)
    {
        $post = Post::where('slug', $slug)->approved()->published()->first();
        $prev = Post::where('id', '<', "$post->id")->latest()->first();
        $next = Post::where('id', '>', "$post->id")->first();

        $blogKey = 'blog_' . $post->id;

        if (!Session::has($blogKey)) {
            $post->increment('view_count');
            Session::put($blogKey, 1);
        }

        return view('new-single', compact('post', 'prev', 'next'));
    }

    public function postByCategory($slug)
    {
        $category = Category::where('slug', $slug)->first();
        $posts    = !empty($category) ? $category->posts()->approved()->published()->paginate(9) : '';

        return view('new-category', compact('category', 'posts'));
    }

    public function postByTag($slug)
    {
        $tag = Tag::where('slug', $slug)->first();
        $posts = !empty($tag) ? $tag->posts()->approved()->published()->paginate(9) : '';

        return view('new-tag', compact('tag', 'posts'));
    }

    public function toc()
    {
        $tocs = Post::latest()->select('title', 'slug')->get();
        $categories = Category::inRandomOrder()->get();

        return view('new-daftar-isi', compact('tocs', 'categories'));
    }
}

Applications/resources/views/admin/post/create.blade.php
@extends('layouts.master')

@section('title','Post')

@push('css')
    <link rel="stylesheet" href="{{ asset('/AdminLTE/plugins/summernote/summernote-bs4.css') }}">
@endpush

@section('breadcrumb')
    @parent
    <li class="breadcrumb-item"><a href="{{ route('admin.post.index') }}">Post</a></li>
    <li class="breadcrumb-item">Add</li>
@endsection

@section('main-content')
<form action="{{ route('admin.post.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-md-8">
            @card
                @slot('title')
                    <h5 class="card-title">Add Post</h5>
                @endslot

                @csrf
                <div class="form-group">
                    <label class="form-label">Post Title</label>
                    <input type="text" id="title" class="form-control" name="title">
                </div>

                <div class="custom-file mt-2">
                    <input type="file" class="custom-file-input" id="customFile" name="image">
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>

                <div class="custom-control custom-checkbox mt-3">
                    <input type="checkbox" class="custom-control-input" id="customCheck1" name="status" value="1">
                    <label class="custom-control-label" for="customCheck1">Publish</label>
                </div>
                
                @slot('footer')
                    
                @endslot
            @endcard
        </div>

        <div class="col-md-4">
            @card
                @slot('title')
                    <h5 class="card-title">Categories and Tags</h5>
                @endslot
                
                <div class="form-group">
                    <label for="category">Select Category</label>
                    <select name="categories[]" id="category" class="form-control" multiple>
                        @foreach($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="tag">Select Tags</label>
                    <select name="tags[]" id="tag" class="form-control" multiple>
                        @foreach($tags as $tag)
                            <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                        @endforeach
                    </select>
                </div>            
                
                @slot('footer')
                    
                @endslot
            @endcard
        </div>
            
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Body</h5>
                </div>
                
                <div class="card-body">
                    <textarea name="body" class="textarea" placeholder="Place some text here" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                </div>

                <div class="card-footer save">
                    <a class="btn btn-danger" href="{{ route('admin.post.index') }}">Back</a>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

@push('scripts')
    <script src="{{ asset('AdminLTE/plugins/summernote/summernote-bs4.min.js') }}"></script>
    <script>

        $(function () {
            $('.textarea').summernote()

            $('select').select2()
            $('.card-footer:not(.save)').hide()

            $('[type=checkbox]').prop('indeterminate', true)
        })
    </script>
@endpush

Applications/resources/views/admin/post/edit.blade.php
@extends('layouts.master')

@section('title','Post')

@push('css')
    <link rel="stylesheet" href="{{ asset('/AdminLTE/plugins/summernote/summernote-bs4.css') }}">
@endpush

@section('breadcrumb')
    @parent
    <li class="breadcrumb-item"><a href="{{ route('admin.post.index') }}">Post</a></li>
    <li class="breadcrumb-item">Add</li>
@endsection

@section('main-content')
<form action="{{ route('admin.post.update',$post->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    
    <div class="row">
        <div class="col-md-8">
            @card
                @slot('title')
                    <h5 class="card-title">Add Post</h5>
                @endslot

                @csrf
                <div class="form-group">
                    <label class="form-label">Post Title</label>
                    <input type="text" id="title" class="form-control" name="title" value="{{ $post->title }}">
                </div>

                <div class="custom-file mt-2">
                    <input type="file" class="custom-file-input" id="customFile" name="image">
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>

                <div class="custom-control custom-checkbox mt-3">
                    <input type="checkbox" class="custom-control-input" id="customCheck1" name="status" value="1" {{ $post->status == true ? 'checked' : '' }}>
                    <label class="custom-control-label" for="customCheck1">Publish</label>
                </div>
                
                @slot('footer')
                    
                @endslot
            @endcard
        </div>

        <div class="col-md-4">
            @card
                @slot('title')
                    <h5 class="card-title">Categories and Tags</h5>
                @endslot
                
                <div class="form-group">
                    <label for="category">Select Category</label>
                    <select name="categories[]" id="category" class="form-control" multiple>
                        @foreach($categories as $category)
                            <option
                                @foreach($post->categories as $postCategory)
                                    {{ $postCategory->id == $category->id ? 'selected' : '' }}
                                @endforeach
                                value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="tag">Select Tags</label>
                    <select name="tags[]" id="tag" class="form-control" multiple>
                       @foreach($tags as $tag)
                            <option
                                @foreach($post->tags as $postTag)
                                    {{ $postTag->id == $tag->id ? 'selected' :'' }}
                                @endforeach
                                value="{{ $tag->id }}">{{ $tag->name }}</option>
                        @endforeach
                    </select>
                </div>            
                
                @slot('footer')
                    
                @endslot
            @endcard
        </div>
            
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Body</h5>
                </div>
                
                <div class="card-body">
                    <textarea name="body" class="textarea" placeholder="Place some text here" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">{{ $post->body }}</textarea>
                </div>

                <div class="card-footer save">
                    <a class="btn btn-danger" href="{{ route('admin.post.index') }}">Back</a>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

@push('scripts')
    <script src="{{ asset('AdminLTE/plugins/summernote/summernote-bs4.min.js') }}"></script>
    <script>

        $(function () {
            $('.textarea').summernote()

            $('select').select2()
            $('.card-footer:not(.save)').hide()

            $('[type=checkbox]').prop('indeterminate', true)
        })
    </script>
@endpush

Applications/resources/views/admin/post/index.blade.php
@extends('layouts.master')

@section('title','Posts')
@section('breadcrumb')
    @parent
    <li class="breadcrumb-item">Posts</li>
@endsection

@section('main-content')
    @card
        @slot('title')
            <a href="{{ route('admin.post.create') }}" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Add</a>
        @endslot
        
        @table

            @slot('thead')
                <th>ID</th>
                <th>Title</th>
                <th>Author</th>
                <th><i class="fas fa-eye"></i></th>
                <th>Is Approved</th>
                <th>Status</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>Action</th>
            @endslot
                                    
            @foreach($posts as $key => $post)
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td title="{{ $post->title }}">{{ str_limit($post->title, '40') }}</td>
                    <td>{{ $post->user->name }}</td>
                    <td>{{ $post->view_count }}</td>
                    <td>
                        @if($post->is_approved == true)
                            <span class="badge bg-primary">Approved</span>
                        @else
                            <span class="badge bg-danger">Pending</span>
                        @endif
                    </td>
                    <td>
                        @if($post->status == true)
                            <span class="badge bg-primary">Published</span>
                        @else
                            <span class="badge bg-danger">Pending</span>
                        @endif
                    </td>
                    <td>{{ $post->created_at->toDateString() }}</td>
                    <td>{{ $post->updated_at->toDateString() }}</td>

                    <td class="text-center">
                        <form action="{{ route('admin.post.destroy', $post->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                             <a href="{{ route('admin.post.show',$post->id) }}" class="btn btn-outline-primary btn-sm"><i class="fas fa-eye"></i></a>
                            <a href="{{ route('admin.post.edit',$post->id) }}" class="btn btn-primary btn-sm"><i class="fas fa-edit"></i></a>
                            <button class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?')"><i class="fas fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
            @endforeach
        @endtable

        @slot('footer')
            
        @endslot
    @endcard
@endsection

@push('scripts')
    <script>
        $('.table').DataTable({
            "language": {
              "emptyTable": "Ups data masih kosong!.",
              "zeroRecords": "Ups data tidak ditemukan!."
            }
        })

        $('.card-footer').hide()
    </script>
@endpush

Applications/resources/views/admin/post/pending.blade.php
@extends('layouts.master')

@section('title','Posts')
@section('breadcrumb')
    @parent
    <li class="breadcrumb-item">Posts</li>
@endsection

@section('main-content')
    @card
        @slot('title')
            <a href="{{ route('admin.post.create') }}" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Add</a>
        @endslot
        
        @table

            @slot('thead')
                <th>ID</th>
                <th>Title</th>
                <th>Author</th>
                <th><i class="fas fa-eye"></i></th>
                <th>Is Approved</th>
                <th>Status</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>Action</th>
            @endslot
                                    
            @foreach($posts as $key => $post)
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td title="{{ $post->title }}">{{ str_limit($post->title, '40') }}</td>
                    <td>{{ $post->user->name }}</td>
                    <td>{{ $post->view_count }}</td>
                    <td>
                        @if($post->is_approved == true)
                            <span class="badge bg-primary">Approved</span>
                        @else
                            <span class="badge bg-danger">Pending</span>
                        @endif
                    </td>
                    <td>
                        @if($post->status == true)
                            <span class="badge bg-primary">Published</span>
                        @else
                            <span class="badge bg-danger">Pending</span>
                        @endif
                    </td>
                    <td>{{ $post->created_at->toDateString() }}</td>
                    <td>{{ $post->updated_at->toDateString() }}</td>

                    <td class="text-center">
                        <form action="{{ route('admin.post.destroy', $post->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                             <a href="{{ route('admin.post.show',$post->id) }}" class="btn btn-outline-primary btn-sm"><i class="fas fa-eye"></i></a>
                            <a href="{{ route('admin.post.edit',$post->id) }}" class="btn btn-primary btn-sm"><i class="fas fa-edit"></i></a>
                            <button class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?')"><i class="fas fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
            @endforeach
        @endtable

        @slot('footer')
            
        @endslot
    @endcard
@endsection

@push('scripts')
    <script>
        $('.table').DataTable({
            "language": {
              "emptyTable": "Ups data masih kosong!.",
              "zeroRecords": "Ups data tidak ditemukan!."
            }
        })

        $('.card-footer').hide()
    </script>
@endpush

Applications/resources/views/admin/post/show.blade.php
@extends('layouts.master')

@section('title', $post->title)
@section('breadcrumb')
    @parent
    <li class="breadcrumb-item">Post</li>
    <li class="breadcrumb-item">Show</li>
@endsection

@section('main-content')
    <div class="row">
        <div class="col-lg-8 col-12">
            @card
                @slot('title')
                    <a href="{{ route('admin.post.index') }}" class="btn btn-danger btn-sm">Back</a>

                    <div class="card-tools">
                          @if($post->is_approved == false)
                            <button type="button" class="btn btn-success waves-effect pull-right" onclick="$('#approval-form').submit()">
                                <i class="fas fa-check"></i>
                                <span>Approve</span>
                            </button>
                            <form method="post" action="{{ route('admin.post.approve', $post->id) }}" id="approval-form" style="display: none">
                                @csrf
                                @method('PUT')
                            </form>
                        
                        @else
                            <button type="button" class="btn btn-success btn-sm" disabled style="cursor: not-allowed;">
                                <i class="fas fa-check"></i>
                                <span>Approved</span>
                            </button>
                        @endif
                    </div>
                @endslot

                <h3>{{ $post->title }}</h3>
                <h5 class="card-title mb-3">
                    Posted By <strong> <a href="">{{ $post->user->name }}</a></strong> on {{ $post->created_at->toFormattedDateString() }}
                </h5>

                {!! $post->body !!}
                
                @slot('footer')
                    
                @endslot
            @endcard
        </div>
        <div class="col-lg-4 col-12">
            @card
                @slot('title')
                    <h5 class="card-title">Categories</h5>
                @endslot

                @foreach($post->categories as $category)
                    <span class="label bg-danger p-1">{{ $category->name }}</span>
                @endforeach

                @slot('footer')
                    
                @endslot
            @endcard

            @card
                @slot('title')
                    <h5 class="card-title">Tags</h5>
                @endslot

                @foreach($post->tags as $tag)
                    <span class="label bg-indigo p-1">{{ $tag->name }}</span>
                @endforeach

                @slot('footer')
                    
                @endslot
            @endcard
            
            @card
                @slot('title')
                    <h5 class="card-title">Featured Image</h5>
                @endslot
                
                <img class="img-fluid" src="{{ Storage::disk('public')->url('post/'. $post->image) }}" alt="">

                @slot('footer')
                    
                @endslot
            @endcard
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $('.card-footer').addClass('d-none d-lg-none')
    </script>
@endpush