Applications/routes/web.php
<?php

Route::get('/home', function () {
    return redirect()->route('admin.dashboard');
});

Route::get('/', 'HomeController@index')->name('home');
Route::get('/articles', 'PostController@index');
Route::get('/daftar-isi', 'PostController@toc');

Route::get('/search', 'SearchController@search')->name('search');
Route::get('/search/getdata', 'SearchController@getData')->name('search.getdata');

Route::get('/templates', function () {
    return view('new-template');
});

Route::get('posts', 'PostController@index')->name('post.index');
Route::get('post/{slug}', 'PostController@detail')->name('post.detail');

Route::get('/category/{slug}', 'PostController@postByCategory')->name('category.posts');
Route::get('/tag/{slug}', 'PostController@postByTag')->name('tag.posts');

Route::post('subscriber', 'SubscriberController@store')->name('subscriber.store');
Auth::routes();

Route::group(['middleware'=> ['auth']], function (){
   Route::post('favorite/{post}/add', 'FavoriteController@add')->name('post.favorite');
   Route::post('comment/{post}', 'CommentController@store')->name('comment.store');
});

Route::group(['as'=>'admin.', 'prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth', 'admin']], function (){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('setting/general', 'SettingsController@index')->name('setting');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    Route::resource('tag', 'TagController');
    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');

    Route::get('/pending/post', 'PostController@pending')->name('post.pending');
    Route::put('/post/{id}/approve', 'PostController@approval')->name('post.approve');

    Route::get('/favorite', 'FavoriteController@index')->name('favorite.index');

    Route::get('authors', 'AuthorController@index')->name('author.index');
    Route::delete('authors/{id}', 'AuthorController@destroy')->name('author.destroy');

    Route::get('comments', 'CommentController@index')->name('comment.index');
    Route::delete('comments/{id}', 'CommentController@destroy')->name('comment.destroy');

    Route::get('/subscriber', 'SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{subscriber}', 'SubscriberController@destroy')->name('subscriber.destroy');
});

Applications/app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public function posts()
    {
        return $this->belongsToMany('App\Post')->withTimestamps();
    }
}

Applications/app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Tag;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::latest()->get();
        return view('admin.tag.index',compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required'
        ]);
        $tag = new Tag();
        $tag->name = $request->name;
        $tag->slug = str_slug($request->name);
        $tag->save();
        Toastr::success('Tag Successfully Saved :)' ,'Success');
        return redirect()->route('admin.tag.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::find($id);
        return view('admin.tag.edit',compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tag = Tag::find($id);
        $tag->name = $request->name;
        $tag->slug = str_slug($request->name);
        $tag->save();
        Toastr::success('Tag Successfully Updated :)','Success');
        return redirect()->route('admin.tag.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Tag::find($id)->delete();
        Toastr::success('Tag Successfully Deleted :)','Success');
        return redirect()->back();
    }
}

Applications/resources/views/admin/tag/create.blade.php
@extends('layouts.master')

@section('title','Tag')

@section('breadcrumb')
    @parent
    <li class="breadcrumb-item"><a href="{{ route('admin.tag.index') }}">Tag</a></li>
    <li class="breadcrumb-item">Add</li>
@endsection

@section('main-content')
    @card
        @slot('title')
            <h5 class="card-title">Add Tag</h5>
        @endslot
        
        <form action="{{ route('admin.tag.store') }}" method="POST">
            @csrf
            <div class="form-group">
                <label for="name">Tag Name</label>
                <input type="text" id="name" class="form-control" name="name">
            </div>
        </form>

        @slot('footer')
            <a class="btn btn-danger" href="{{ route('admin.tag.index') }}">Back</a>
            <button type="submit" class="btn btn-primary" onclick="$('form').submit()">Save</button>
        @endslot
    @endcard
@endsection

Applications/resources/views/admin/tag/edit.blade.php
@extends('layouts.master')

@section('title','Tag')
@section('breadcrumb')
    @parent
    <li class="breadcrumb-item"><a href="{{ route('admin.tag.index') }}">Tag</a></li>
    <li class="breadcrumb-item">Edit</li>
@endsection

@section('main-content')
    @card
        @slot('title')
            <h5 class="card-title">Edit Tag</h5>
        @endslot
        
        <form action="{{ route('admin.tag.update',$tag->id) }}" method="POST">
            @csrf 
            @method('PUT')

            <div class="form-group">
                <label for="name">Tag Name</label>
                <input type="text" id="name" class="form-control" name="name" value="{{ $tag->name }}">
            </div>
        </form>

        @slot('footer')
            <a class="btn btn-danger" href="{{ route('admin.tag.index') }}">Back</a>
            <button type="submit" class="btn btn-primary" onclick="$('form').submit()">Save</button>
        @endslot
    @endcard
@endsection

Applications/resources/views/admin/tag/index.blade.php
@extends('layouts.master')

@section('title','Tags')
@section('breadcrumb')
    @parent
    <li class="breadcrumb-item">Tags</li>
@endsection

@section('main-content')
    @card
        @slot('title')
            <a href="{{ route('admin.tag.create') }}" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Add</a>
        @endslot
        
        @table
            @slot('thead')
                <th>ID</th>
                <th>Name</th>
                <th>Post Count</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>Action</th>
            @endslot

            @foreach($tags as $key => $tag)
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td>{{ $tag->name }}</td>
                    <td>{{ $tag->posts->count() }}</td>
                    <td>{{ $tag->created_at->toDateString() }}</td>
                    <td>{{ $tag->updated_at->toDateString() }}</td>
                    <td class="text-center">
                        <form action="{{ route('admin.tag.destroy', $tag->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <a href="{{ route('admin.tag.edit',$tag->id) }}" class="btn btn-primary btn-sm"><i class="fas fa-edit"></i></a>
                            <button class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?')"><i class="fas fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
            @endforeach
        @endtable
        @slot('footer')
            
        @endslot
    @endcard
@endsection

@push('scripts')
    <script>
        $('.table').DataTable({
            "language": {
              "emptyTable": "Ups data masih kosong!.",
              "zeroRecords": "Ups data tidak ditemukan!."
            }
        })

        $('.card-footer').hide()
    </script>
@endpush