Applications/routes/web.php
<?php

Route::get('/home', function () {
    return redirect()->route('admin.dashboard');
});

Route::get('/', 'HomeController@index')->name('home');
Route::get('/articles', 'PostController@index');
Route::get('/daftar-isi', 'PostController@toc');

Route::get('/search', 'SearchController@search')->name('search');
Route::get('/search/getdata', 'SearchController@getData')->name('search.getdata');

Route::get('/templates', function () {
    return view('new-template');
});

Route::get('posts', 'PostController@index')->name('post.index');
Route::get('post/{slug}', 'PostController@detail')->name('post.detail');

Route::get('/category/{slug}', 'PostController@postByCategory')->name('category.posts');
Route::get('/tag/{slug}', 'PostController@postByTag')->name('tag.posts');

Route::post('subscriber', 'SubscriberController@store')->name('subscriber.store');
Auth::routes();

Route::group(['middleware'=> ['auth']], function (){
   Route::post('favorite/{post}/add', 'FavoriteController@add')->name('post.favorite');
   Route::post('comment/{post}', 'CommentController@store')->name('comment.store');
});

Route::group(['as'=>'admin.', 'prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth', 'admin']], function (){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('setting/general', 'SettingsController@index')->name('setting');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    Route::resource('tag', 'TagController');
    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');

    Route::get('/pending/post', 'PostController@pending')->name('post.pending');
    Route::put('/post/{id}/approve', 'PostController@approval')->name('post.approve');

    Route::get('/favorite', 'FavoriteController@index')->name('favorite.index');

    Route::get('authors', 'AuthorController@index')->name('author.index');
    Route::delete('authors/{id}', 'AuthorController@destroy')->name('author.destroy');

    Route::get('comments', 'CommentController@index')->name('comment.index');
    Route::delete('comments/{id}', 'CommentController@destroy')->name('comment.destroy');

    Route::get('/subscriber', 'SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{subscriber}', 'SubscriberController@destroy')->name('subscriber.destroy');
});

Applications/resources/views/layouts/partials/footer.blade.php
<!-- Main Footer -->
<footer class="main-footer">
	<!-- To the right -->
	<div class="float-right d-none d-sm-inline">
		Created with <i class="fas fa-heart text-danger" style="font-size: .8em"></i> by Nursandi
	</div>
	<!-- Default to the left -->
	<strong>Copyright &copy; 2017-2019 <a href="https://w2learn.com">W2Learn.com</a>.</strong> All rights reserved.
</footer>

Applications/resources/views/layouts/partials/nav.blade.php
<nav class="main-header navbar navbar-expand bg-indigo navbar-dark">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link d-none d-lg-block" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>

            <a href="#" class="nav-link d-lg-none d-block"  data-widget="pushmenu" style="margin-left: -1em;">
                <img src="{{ asset('/img/icon.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3">
                <span class="brand-text font-weight-light" style="font-size: 1.5em">W2Learn CMS</span>
            </a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <a href="{{ route('home') }}" class="nav-item nav-link" title="Go To Website."><i class="fas fa-reply-all"></i></a>
        <a href="{{ route('logout') }}" class="nav-item nav-link" onclick="event.preventDefault(); document.getElementById('logout-form').submit()"><i class="fas fa-sign-out-alt"></i> Sign Out</a>
        <form action="{{ route('logout') }}" method="post" class="d-none d-lg-none" id="logout-form">
            @csrf
        </form>
    </ul>
</nav>

Applications/resources/views/layouts/partials/sidebar.blade.php
<aside class="main-sidebar sidebar-light-indigo elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link navbar-indigo text-white">
        <img src="{{ asset('/img/icon.png') }}" alt="W2learn Logo" class="brand-image img-circle elevation-3">
        <span class="brand-text font-weight-light">W2Learn CMS</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ Storage::disk('public')->url('profile/'. Auth::user()->image) }}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="{{ route('admin.setting') }}" class="d-block">{{ Auth::user()->name }}</a>
            </div>
        </div>
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                @if(Request::is('admin*'))
                
                <li class="nav-item">
                    <a href="{{ route('admin.dashboard') }}" class="nav-link {{ Request::is('admin/dashboard') ? 'active' : '' }}">
                        <i class="nav-icon fas fa-home"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="nav-header">MAIN NAVIGATION</li>
                <li class="nav-item">
                    <a href="{{ route('admin.tag.index') }}" class="nav-link {{ Request::is('admin/tag*') ? 'active' : '' }}">
                        <i class="nav-icon fas fa-tag"></i>
                        <p>Tags</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.category.index') }}" class="nav-link {{ Request::is('admin/category*') ? 'active' : '' }}">
                        <i class="nav-icon fas fa-th-list"></i>
                        <p>Categories</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.post.index') }}" class="nav-link {{ Request::is('admin/post*') ? 'active' : '' }}">
                        <i class="nav-icon fas fa-book"></i>
                        <p>Posts</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.post.pending') }}" class="nav-link {{ Request::is('admin/pending/post') ? 'active' : '' }}">
                        <i class="nav-icon fas fa-book"></i>
                        <p>Pending Posts</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.favorite.index') }}" class="nav-link {{ Request::is('admin/favorite') ? 'active' : '' }}">
                        <i class="nav-icon fas fa-heart"></i>
                        <p>Favorite Posts</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.comment.index') }}" class="nav-link {{ Request::is('admin/comments') ? 'active' : '' }}">
                        <i class="nav-icon fas fa-comments"></i>
                        <p>Comments</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.author.index') }}" class="nav-link {{ Request::is('admin/authors') ? 'active' : '' }}">
                        <i class="nav-icon fas fa-user-circle"></i>
                        <p>Authors</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.subscriber.index') }}" class="nav-link {{ Request::is('admin/subscriber') ? 'active' : '' }}">
                        <i class="nav-icon fas fa-users"></i>
                        <p>Subscribers</p>
                    </a>
                </li>
                <li class="nav-header">SYSTEM</li>

                <li class="nav-item">
                    <a href="{{ route('admin.setting') }}" class="nav-link {{ Request::is('admin/setting/general') ? 'active' : '' }}">
                        <i class="nav-icon fas fa-cogs"></i>
                        <p>Setting</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('logout') }}"
                       onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        <i class="nav-icon fas fa-sign-out-alt"></i>
                        <p>Sign Out</p>
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </li>
                @endif
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>